<?php
function netmaster_english_page(string $source, string $currentRoute): void
{
    ob_start();
    require $source;
    $html = ob_get_clean();

    $translations = [
        'lang="de"' => 'lang="en"',
        'Netmaster — Business neu vernetzt' => 'Netmaster — Reconnecting business',
        'Netmaster Startseite' => 'Netmaster homepage',
        'Über uns' => 'About us', 'Dienstleistungen' => 'Services', 'Kontakt' => 'Contact',
        'Deutsch' => 'German', 'English' => 'English', 'Jobsmaster' => 'Jobsmaster', 'Jobs' => 'Careers',
        'Impressum · Datenschutz · AGB' => 'Legal notice · Privacy · Terms',
        'Jahre Erfahrung' => 'Years of experience', 'Mehr erfahren' => 'Learn more', 'Erfahren Sie mehr' => 'Learn more',
        'Website besuchen' => 'Visit website', 'Besuche unsere Webseite' => 'Visit our website',
        'Kontakt aufnehmen' => 'Get in touch', 'Nachricht senden' => 'Send message',
        'Menschen verbinden.' => 'Connecting people.', 'Ideen bewegen.' => 'Moving ideas.',
        'Erfolg gestalten.' => 'Shaping success.', 'Unsere Geschichte' => 'Our story',
        'Unsere Themen' => 'Our expertise', 'Menschen mit Haltung.' => 'People with purpose.',
        'Unsere Ideen bringen Ihnen den Erfolg.' => 'Our ideas drive your success.',
        'Gemeinsam stärker.' => 'Stronger together.',
        'Selbstständig.' => 'Independent.', 'Nicht allein.' => 'Never alone.',
        'Jetzt Partner werden' => 'Become a partner', 'System entdecken' => 'Discover the system',
        'Was Sie mitbringen.' => 'What you bring.', 'Was wir Ihnen bieten.' => 'What we offer.',
        'Der nächste Schritt' => 'The next step',
        'Die richtigen Experten' => 'The right experts', 'für jede Herausforderung.' => 'for every challenge.',
        'Unsere Business Units' => 'Our business units', 'Business Units entdecken' => 'Explore business units',
        'Wir finden gemeinsam die passende Lösung.' => 'Together, we find the right solution.',
        'Ideen werden' => 'Ideas become', 'digital wirksam.' => 'digitally effective.',
        'Webagentur und digitale Inhalte' => 'Web agency and digital content',
        'Wer ist Marketingmaster' => 'Who is Marketingmaster',
        'Was wir bei Marketingmaster tun' => 'What we do at Marketingmaster',
        'Bereit, Ihre Marke sichtbar zu machen?' => 'Ready to make your brand visible?',
        'Vertrieb, der' => 'Sales that', 'Wachstum bewegt.' => 'drive growth.',
        'Über Salesmaster' => 'About Salesmaster', 'Was wir bei Salesmaster tun' => 'What we do at Salesmaster',
        'Kompetenz für Ihren Vertrieb.' => 'Expertise for your sales.',
        'Bringen wir Ihren Vertrieb in Bewegung.' => 'Let’s move your sales forward.',
        'Jede Stimme' => 'Every voice', 'zählt.' => 'matters.',
        'Wer ist Callmaster' => 'Who is Callmaster', 'Was Callmaster leistet' => 'What Callmaster delivers',
        'Machen wir jeden Kontakt wertvoll.' => 'Let’s make every contact count.',
        'Exklusive Werte.' => 'Exclusive values.', 'Diskret vermittelt.' => 'Discreetly connected.',
        'Wer wir sind' => 'Who we are', 'Unser Mehrwert' => 'Our added value',
        'Für wen wir arbeiten' => 'Who we work for',
        'Immobilienberatung auf höchstem Niveau.' => 'Real estate consulting at the highest level.',
        'Menschen finden.' => 'Finding people.', 'Zukunft gestalten.' => 'Shaping the future.',
        'Personalbeschaffung und Vermittlung' => 'Recruitment and placement',
        'Wer ist Jobsmaster' => 'Who is Jobsmaster', 'Was Jobsmaster leistet' => 'What Jobsmaster delivers',
        'Talente, die wirklich passen.' => 'Talent that truly fits.',
        'Lassen Sie uns' => 'Let’s start', 'ins Gespräch kommen.' => 'a conversation.',
        'Ihre Anfrage' => 'Your enquiry', 'Womit können wir Ihnen helfen?' => 'How can we help you?',
        'Unsere Standorte' => 'Our locations', 'Zwei Standorte.' => 'Two locations.',
        'Ein gemeinsames Netzwerk.' => 'One shared network.', 'Route öffnen' => 'Open directions',
        'Karriere bei Netmaster' => 'Careers at Netmaster', 'Gemeinsam Zukunft' => 'Shape the future',
        'gestalten.' => 'together.', 'Offene Stellen' => 'Open positions',
        'Spontanbewerbung' => 'General application', 'Aktueller Status' => 'Current status',
        'Momentan sind keine offenen Stellen verfügbar.' => 'There are currently no open positions.',
        'Vielleicht passen wir trotzdem zusammen.' => 'We may still be a great match.',
        'Vorname' => 'First name', 'Nachname' => 'Last name', 'Telefonnummer' => 'Phone number',
        'Ihre Nachricht' => 'Your message', 'Lebenslauf' => 'CV', 'Bitte auswählen' => 'Please select',
        'Spontanbewerbung senden' => 'Send general application',
        'Willkommen' => 'Welcome', 'zurück.' => 'back.', 'Netmaster Kundenportal' => 'Netmaster client portal',
        'Bei Netmaster anmelden' => 'Sign in to Netmaster', 'Geben Sie Ihre Zugangsdaten ein.' => 'Enter your login details.',
        'Passwort' => 'Password', 'Angemeldet bleiben' => 'Keep me signed in',
        'Passwort vergessen?' => 'Forgot password?', 'Anmelden' => 'Sign in',
        'Noch kein Konto?' => 'No account yet?', 'Jetzt registrieren' => 'Register now',
        'Gemeinsam mehr.' => 'Achieve more.', 'Gemeinsam weiter.' => 'Move forward together.',
        'Konto erstellen' => 'Create account', 'Registrierung' => 'Registration',
        'Unternehmen' => 'Company', 'Passwort bestätigen' => 'Confirm password',
        'Bereits registriert?' => 'Already registered?', 'Jetzt anmelden' => 'Sign in now',
        'E-Mail-Adresse' => 'Email address'
    ];

    $serviceTranslations = require __DIR__ . '/service-translations.php';
    if (isset($serviceTranslations[$currentRoute])) {
        $translations = array_merge($translations, $serviceTranslations[$currentRoute]);
    }

    if ($currentRoute === '/en') {
        $translations = array_merge($translations, [
            'Business neu' => 'Business, newly',
            'vernetzt.' => 'connected.',
            'Ihr Netzwerk für Wachstum' => 'Your network for growth',
            'Wir verbinden Menschen, Prozesse und Technologie – damit Sie sich auf das konzentrieren können, was Ihr Unternehmen einzigartig macht.' => 'We connect people, processes and technology — so you can focus on what makes your business unique.',
            'Projekt starten' => 'Start a project',
            'Outsourcing & Business Solutions · seit 2008' => 'Outsourcing & Business Solutions · since 2008',
            'Ihr Outsourcing-Experte' => 'Your outsourcing expert',
            'Jahre Outsourcing-Erfahrung' => 'Years of outsourcing experience',
            'Zürich · Lugano · Stuttgart' => 'Zurich · Lugano · Stuttgart',
            'Gemeinsam erfolgreich' => 'Successful together',
            'Starke Marken.' => 'Strong brands.',
            'Langfristiges Vertrauen.' => 'Long-term trust.',
            'Wir haben das Privileg, Unternehmen aus unterschiedlichsten Branchen mit unserem Netzwerk und unserer Erfahrung zu unterstützen.' => 'We have the privilege of supporting companies across a wide range of industries with our network and experience.',
            'Willkommen bei' => 'Welcome to',
            'Vorteile von Outsourcing' => 'The benefits of outsourcing',
            'Outsourcen Sie Ihre Geschäftsfelder aus. Wir helfen Ihnen dabei, während Sie sich auf Ihr Kerngeschäft konzentrieren.' => 'Outsource selected areas of your business. We support you while you focus on your core operations.',
            'Das Wort Outsourcing kommt aus dem Englischen und bezieht sich auf einzelne Aufgaben, Teilbereiche oder Geschäftsprozesse, welche von Unternehmen an externe Firmen ausgelagert werden.' => 'Outsourcing refers to individual tasks, business areas or processes that a company delegates to external specialists.',
            'Dank der Auslagerung gewisser Geschäftsbereiche geniessen Sie viele Vorteile, wie zum Beispiel Ersparnisse bei der Produktion in globalisierten Märkten. Ausserdem können Sie das unternehmerische Risiko senken, was in angespannten wirtschaftlichen Zeiten nützlich ist.' => 'By outsourcing selected business areas, you benefit from advantages such as cost savings in globalised markets. You can also reduce business risk, which is particularly valuable in challenging economic conditions.',
            'Im Gebiet Outsourcing sind wir langjährige Experte. Profitieren Sie von unserem Netzwerk mit Spezialisten im Bereich' => 'We have many years of outsourcing expertise. Benefit from our network of specialists in',
            'Wir suchen für Ihr Unternehmen die passende Lösung. Durch die freiwerdenden Ressourcen können Sie in Ihr Hauptgeschäft investieren und somit die Qualität, Effektivität und Ihre Marktposition verbessern.' => 'We find the right solution for your company. The resources you gain can be reinvested in your core business to improve quality, effectiveness and your market position.',
            'Kostenlose Analyse anfordern' => 'Request a free analysis',
            'Kostenlose Analyse' => 'Free analysis',
            'Unsere Werte' => 'Our values',
            'Was bieten Wir Ihnen?' => 'What do we offer?',
            'Philosophie' => 'Philosophy',
            'Unsere hochmotivierten Mitarbeiter versuchen stets Ihr Unternehmen nachhaltig und wirtschaftlich zum Erfolg zu führen.' => 'Our highly motivated employees work to guide your company towards sustainable and commercial success.',
            'Wir möchten unseren Kunden nur den besten und professionellsten Service bieten, der Sie zum Erfolg führt.' => 'We want to provide our clients with the best and most professional service to help them succeed.',
            'Offene Stellen' => 'Open positions',
            'Wer Interesse an einem abwechslungsreichen und fordernden Job im Bereich Marketing hat, der sollte sich bei uns um eine Anstellung (m/w) bewerben.' => 'If you are interested in a varied and challenging role in marketing, we would be pleased to receive your application.',
            'Stellen ansehen' => 'View positions',
            'Unsere Philosophie' => 'Our philosophy',
            'Lösungen für Ihre Herausforderung' => 'Solutions for your challenge',
            'Tägliche Bestleistung' => 'Excellence every day',
            'Unsere Mitarbeiter arbeiten leidenschaftlich, um Ihr Unternehmen auf Erfolgskurs zu bringen.' => 'Our employees work passionately to put your company on the path to success.',
            'Die Mitarbeiter sind das Herz des Unternehmens' => 'Employees are the heart of the company',
            'Langfristig sichere Arbeitsplätze zu gewährleisten ist unser oberstes Ziel.' => 'Ensuring secure, long-term employment is one of our highest priorities.',
            'Kundenzufriedenheit' => 'Customer satisfaction',
            'Es ist für uns selbstverständlich, unsere Kunden von Anfang an kompetent und professionell zu beraten und unser Know-how und die langjährige Erfahrung in Ihr Projekt einfliessen zu lassen.' => 'We provide competent, professional advice from the outset and bring our expertise and many years of experience to every project.',
            'Fachwissen' => 'Expertise',
            'Hingabe' => 'Dedication',
            'Kreativität' => 'Creativity',
            'Erfahrung' => 'Experience',
            'Unsere Standorte' => 'Our locations',
            'Persönlich für Sie da.' => 'Here for you personally.',
            'Wählen Sie einen Standort, um ihn direkt auf der Karte anzuzeigen.' => 'Choose a location to display it directly on the map.',
            'Hauptsitz · Schweiz' => 'Head office · Switzerland',
            'Filiale · Schweiz' => 'Branch office · Switzerland',
            'Route in Google Maps' => 'Directions in Google Maps',
            'Direkter Kontakt' => 'Direct contact',
            'Was dürfen wir für Sie einfacher machen?' => 'What can we make easier for you?',
            'Erzählen Sie uns kurz von Ihrer Herausforderung. Wir melden uns persönlich und unverbindlich.' => 'Tell us briefly about your challenge. We will get back to you personally and without obligation.',
            'Name *' => 'Name *',
            'E-Mail *' => 'Email *',
            'Unternehmen' => 'Company',
            'Ihre Herausforderung *' => 'Your challenge *',
            'Ihre Daten werden vertraulich behandelt.' => 'Your information will be treated confidentially.',
            'Anfrage absenden →' => 'Send enquiry →',
            'Vielen Dank,' => 'Thank you,',
            'Ihre Anfrage wurde lokal validiert. Für den Live-Betrieb wird hier der E-Mail-Versand angeschlossen.' => 'Your enquiry has been validated. Email delivery still needs to be connected for production use.',
            'Bitte geben Sie Ihren Namen ein.' => 'Please enter your name.',
            'Bitte geben Sie eine gültige E-Mail-Adresse ein.' => 'Please enter a valid email address.',
            'Bitte beschreiben Sie kurz Ihre Herausforderung.' => 'Please briefly describe your challenge.',
            'Leistungen' => 'Services',
            'Netmaster (Schweiz) AG' => 'Netmaster (Switzerland) Ltd.',
            'Impressum · Datenschutz · AGB' => 'Legal notice · Privacy · Terms'
        ]);
    }

    if ($currentRoute === '/en/about-us') {
        $translations = array_merge($translations, [
            'Über uns — Netmaster' => 'About us — Netmaster',
            'Über Netmaster' => 'About Netmaster',
            'Wir bringen Menschen, Expertise und Technologie zusammen – für Lösungen, die Unternehmen nachhaltig voranbringen.' => 'We bring people, expertise and technology together — creating solutions that move companies forward sustainably.',
            'Gegründet 2008 · Schweiz' => 'Founded in 2008 · Switzerland',
            'Jahre Erfahrung in Business Solutions' => 'Years of experience in business solutions',
            'Unsere Themen' => 'Our expertise',
            'Wir arbeiten mit Leidenschaft an folgenden Themen' => 'We are passionate about the following topics.',
            'Geschäftsleitung' => 'Executive management',
            'Menschen mit Haltung.' => 'People with purpose.',
            'Jeder einzelne Mitarbeiter trägt mit seinem Talent, seinem Know-how und seiner Erfahrung zum Gesamterfolg des Unternehmens bei.' => 'Every employee contributes their talent, expertise and experience to the company’s overall success.',
            'Mitglied der Geschäftsleitung' => 'Member of the executive management team',
            'Gemeinsam weiter' => 'Moving forward together',
            'Unsere Ideen bringen Ihnen den Erfolg.' => 'Our ideas drive your success.',
            'Jeder einzelne Mitarbeiter trägt mit seinem Talent, seinem Know-how und seiner langjährigen Erfahrung seinen Teil zum Gesamterfolg des Unternehmens bei.' => 'Every employee contributes their talent, expertise and many years of experience to the company’s overall success.',
            'Lernen Sie uns und unsere Mitarbeiter kennen. Wir führen Sie und Ihr Unternehmen mit grosser Sicherheit zum Erfolg. Vertrauen Sie auf unsere langjährige Erfahrung in den Bereichen Sales, Marketing & Human Resources.' => 'Get to know us and our team. We guide you and your company towards success with confidence. Rely on our many years of experience in sales, marketing and human resources.',
            'Unverbindliches Angebot anfordern →' => 'Request a no-obligation proposal →',
            'Unsere Philosophie' => 'Our philosophy',
            'Verantwortung für Menschen und Ergebnisse.' => 'Responsibility for people and results.',
            'Tägliche Bestleistung' => 'Excellence every day',
            'Unsere hochmotivierten Mitarbeiter versuchen stets Ihr Unternehmen nachhaltig und wirtschaftlich zum Erfolg zu führen.' => 'Our highly motivated employees work to guide your company towards sustainable and commercial success.',
            'Die Mitarbeiter sind das Herz des Unternehmens' => 'Employees are the heart of the company',
            'Langfristig sichere Arbeitsplätze zu gewährleisten ist unser oberstes Ziel. Denn nur Mitarbeiter mit Zukunftsperspektiven können sich voll und ganz für den Kunden einsetzen.' => 'Ensuring secure, long-term employment is our highest priority. Only employees with a clear future can fully dedicate themselves to our clients.',
            'Kundenzufriedenheit' => 'Customer satisfaction',
            'Wir beraten unsere Kunden von Anfang an kompetent und professionell und lassen unser Know-how und unsere Erfahrung in jedes Projekt einfliessen.' => 'We advise our clients competently and professionally from the outset, bringing our expertise and experience to every project.',
            'Partner' => 'Partners',
            'Gemeinsam stärker.' => 'Stronger together.',
            'Wir bieten Ihnen die Möglichkeit, die Angebote unserer leistungsstarken Partnerunternehmen zu prüfen. Das Partnernetzwerk umfasst Berater und Dienstleister, die unsere Kernkompetenzen in Sales, Marketing & Human Resources optimal ergänzen.' => 'We give you access to the services of our high-performing partner companies. Our partner network includes consultants and service providers who complement our core expertise in sales, marketing and human resources.',
            'Die beste Leistung kann nur der erbringen, der sich auf seine Kompetenzen konzentriert und diese kontinuierlich verbessert.' => 'The best results come from focusing on core strengths and improving them continuously.',
            'Partnerschaft besprechen' => 'Discuss a partnership',
            'Netmaster (Schweiz) AG' => 'Netmaster (Switzerland) Ltd.'
        ]);
    }

    if ($currentRoute === '/en/franchising') {
        $translations = array_merge($translations, [
            'Franchising — Netmaster' => 'Franchising — Netmaster',
            'Netmaster Franchising' => 'Netmaster Franchising',
            'Selbstständig.' => 'Independent.',
            'Nicht allein.' => 'Never alone.',
            'Werden Sie eigenständiger Unternehmer innerhalb eines professionellen, klar strukturierten Franchisesystems – mit exklusivem Gebiet und einem starken Netzwerk an Ihrer Seite.' => 'Become an independent entrepreneur within a professional, clearly structured franchise system — with an exclusive territory and a strong network by your side.',
            'Jetzt Partner werden →' => 'Become a partner →',
            'System entdecken ↓' => 'Discover the system ↓',
            'Jahre Erfahrung' => 'Years of experience',
            'Business-Kompetenz' => 'Business expertise',
            'Unterstützung' => 'Support',
            'Ihr Gebiet.' => 'Your territory.',
            'Ihr Unternehmen.' => 'Your company.',
            'Unser System.' => 'Our system.',
            'Ein starkes Unternehmen braucht' => 'A strong company needs',
            'starke Franchisepartner.' => 'strong franchise partners.',
            'Unser Franchisesystem bietet eine einzigartige Perspektive für diejenigen, die danach streben, selbstständige Unternehmer im Rahmen eines professionellen Franchisesystems zu werden.' => 'Our franchise system offers a unique opportunity for people who want to become independent entrepreneurs within a professional franchise structure.',
            'Unser Franchisesystem hebt sich im Franchise-Bereich ab, indem es Geschäftsinhabern und aufstrebenden Unternehmern die exklusive Gelegenheit bietet, als eigenständige Franchisenehmer innerhalb eines klar strukturierten Systems zu agieren. Diese Partnerschaft zeigt sich in der operativen Tätigkeit in einem exklusiven Gebiet unter der Führung der Netmaster (Schweiz) AG, wodurch eine privilegierte Marktposition sichergestellt wird.' => 'Our franchise system stands apart by offering business owners and aspiring entrepreneurs the exclusive opportunity to operate independently within a clearly structured framework. Partners work in an exclusive territory under the guidance of Netmaster (Switzerland) Ltd., creating a privileged position in the market.',
            'Unser Franchisesystem positioniert sich im Markt wie ein Schweizer Taschenmesser und steht damit für einen vielseitigen, strukturierten und präzisen Ansatz im Franchising. Es repräsentiert ein bewährtes Franchisekonzept, das verschiedene Geschäftswerkzeuge vereint und Franchisenehmern eine solide Grundlage für nachhaltigen Erfolg in Bereichen wie Marketing, Vertrieb und Photovoltaik bietet.' => 'Our franchise system is positioned like the Swiss Army knife of the business world: versatile, structured and precise. It combines proven business tools and gives franchise partners a solid foundation for sustainable success in areas such as marketing, sales and photovoltaics.',
            'Unser Franchisesystem umfasst zentrale Geschäftsbereiche wie Immobilien, IT, Human Resources, Call Center, E-Commerce sowie Mergers &amp; Acquisitions und stellt Franchisenehmern eine breite Palette an erprobten, leistungsstarken Tools zur Verfügung, die den Erfolg im unternehmerischen Alltag unterstützen.' => 'Our franchise system covers key business areas such as real estate, IT, human resources, call centres, e-commerce, and mergers &amp; acquisitions. Franchise partners gain access to a broad range of proven, high-performance tools that support success in everyday business.',
            'Ihre Perspektive' => 'Your opportunity',
            'Was Sie mitbringen.' => 'What you bring.',
            'Was wir Ihnen bieten.' => 'What we offer.',
            'Voraussetzungen sind:' => 'What we are looking for:',
            'Unternehmerisches Denken mit starkem Erfolgswillen.' => 'An entrepreneurial mindset and a strong determination to succeed.',
            'Bereitschaft, zeitliche, intellektuelle und finanzielle Ressourcen in die eigene Unabhängigkeit zu investieren.' => 'A willingness to invest time, knowledge and financial resources in your own independence.',
            'Hohe Neigung, effiziente Ergebnisse zu erzielen.' => 'A strong focus on achieving efficient, measurable results.',
            'Unser Franchising-System bietet Ihnen:' => 'Our franchise system offers you:',
            'Beschleunigte Unabhängigkeit mit einer innovativen Methode.' => 'A faster path to independence through an innovative method.',
            'Intensive und praxisorientierte Schulung.' => 'Intensive, practice-oriented training.',
            'Exklusives Gebiet und kontinuierliche Unterstützung für das Wachstum Ihres Unternehmens.' => 'An exclusive territory and continuous support for your company’s growth.',
            'Faire Partnerschaft und ein erprobtes Franchisesystem.' => 'A fair partnership and a proven franchise system.',
            '15 Jahre Erfahrung in einzigartigen und fortschrittlichen Lösungen.' => '15 years of experience delivering distinctive, forward-looking solutions.',
            'Der nächste Schritt' => 'The next step',
            'Innovieren Sie mit unserem Franchising-System.' => 'Build your future with our franchise system.',
            'Nutzen Sie die Vielseitigkeit des Schweizer Taschenmessers der Geschäftswelt, um Ihre unternehmerische Karriere zu schärfen.' => 'Use the versatility of the Swiss Army knife of the business world to sharpen your entrepreneurial career.',
            'Kontakt aufnehmen →' => 'Get in touch →',
            'Netmaster (Schweiz) AG' => 'Netmaster (Switzerland) Ltd.'
        ]);
    }

    if ($currentRoute === '/en/services') {
        $translations = array_merge($translations, [
            'Dienstleistungen — Netmaster' => 'Services — Netmaster',
            'Unsere Business Units' => 'Our business units',
            'Die richtigen Experten' => 'The right experts',
            'für jede Herausforderung.' => 'for every challenge.',
            'Fünf spezialisierte Business Units. Ein gemeinsames Ziel: Ihr Unternehmen mit fundierter Expertise, starken Teams und messbaren Lösungen voranzubringen.' => 'Five specialised business units. One shared goal: moving your company forward through proven expertise, strong teams and measurable solutions.',
            'Business Units entdecken ↓' => 'Explore business units ↓',
            'Kompetenz aus einer Hand' => 'Expertise from one source',
            'Wählen Sie den Bereich, der Sie weiterbringt.' => 'Choose the business area that moves you forward.',
            'Online Marketing Agentur' => 'Online marketing agency',
            'E-Commerce · Webdesign · SEO' => 'E-commerce · Web design · SEO',
            'Virtual Tour · Social Media' => 'Virtual tours · Social media',
            'Marketing entdecken ↗' => 'Explore marketing ↗',
            'Headhunting Sales' => 'Sales headhunting',
            'Recruiting · Head of Sales' => 'Recruiting · Head of Sales',
            'Verkaufsleiter · Key Account' => 'Sales management · Key accounts',
            'Sales entdecken ↗' => 'Explore sales ↗',
            'Telemarketing' => 'Telemarketing',
            'Digital Lösungen' => 'Digital solutions',
            'Callmaster entdecken ↗' => 'Explore Callmaster ↗',
            'Property' => 'Property',
            'Real Estate' => 'Real estate',
            'Immobilien entdecken ↗' => 'Explore real estate ↗',
            'Recruiting' => 'Recruiting',
            'Personalvermittlung' => 'Personnel placement',
            'Diverse Branchen' => 'Multiple industries',
            'Talente entdecken ↗' => 'Explore talent ↗',
            'Nicht sicher, wo Sie starten?' => 'Not sure where to start?',
            'Wir finden gemeinsam die passende Lösung.' => 'Together, we will find the right solution.',
            'Projekt besprechen →' => 'Discuss your project →',
            'Netmaster (Schweiz) AG' => 'Netmaster (Switzerland) Ltd.'
        ]);
    }

    if ($currentRoute === '/en/contact') {
        $translations = array_merge($translations, [
            'Kontakt — Netmaster' => 'Contact — Netmaster',
            'Kontaktieren Sie Netmaster in Wädenswil oder Lugano.' => 'Contact Netmaster in Wädenswil or Lugano.',
            'Lassen Sie uns' => 'Let’s start',
            'ins Gespräch kommen.' => 'a conversation.',
            'Haben Sie Fragen zu unseren Dienstleistungen? Wir freuen uns auf Ihre Nachricht und melden uns persönlich bei Ihnen.' => 'Do you have questions about our services? We look forward to hearing from you and will respond personally.',
            'Ihre Anfrage' => 'Your enquiry',
            'Womit können wir Ihnen helfen?' => 'How can we help you?',
            'Füllen Sie das Formular aus. Pflichtfelder sind mit einem Stern gekennzeichnet.' => 'Complete the form below. Required fields are marked with an asterisk.',
            'Persönliche Rückmeldung' => 'Personal response',
            'In der Regel innerhalb eines Arbeitstages.' => 'Usually within one business day.',
            'Vielen Dank,' => 'Thank you,',
            'Ihre Anfrage wurde erfolgreich validiert. Für den Live-Betrieb muss noch der E-Mail-Versand angeschlossen werden.' => 'Your enquiry has been validated successfully. Email delivery still needs to be connected for production use.',
            'Nachname *' => 'Last name *',
            'Vorname *' => 'First name *',
            'Strasse' => 'Street',
            'Ort / PLZ' => 'City / postcode',
            'Telefonnummer' => 'Phone number',
            'E-Mail *' => 'Email *',
            'Zusätzliche Informationen *' => 'Additional information *',
            'Beim Absenden des Formulars akzeptiere ich die' => 'By submitting this form, I accept the',
            'Datenschutzvereinbarung' => 'privacy policy',
            'Nachricht senden →' => 'Send message →',
            'Unsere Standorte' => 'Our locations',
            'Zwei Standorte.' => 'Two locations.',
            'Ein gemeinsames Netzwerk.' => 'One shared network.',
            'Hauptsitz · Schweiz' => 'Head office · Switzerland',
            'Filiale · Schweiz' => 'Branch office · Switzerland',
            'Route öffnen ↗' => 'Open directions ↗',
            'Bitte geben Sie Ihren Nachnamen ein.' => 'Please enter your last name.',
            'Bitte geben Sie Ihren Vornamen ein.' => 'Please enter your first name.',
            'Bitte geben Sie eine gültige E-Mail-Adresse ein.' => 'Please enter a valid email address.',
            'Bitte schreiben Sie uns eine kurze Nachricht.' => 'Please write us a short message.',
            'Bitte akzeptieren Sie die Datenschutzvereinbarung.' => 'Please accept the privacy policy.',
            'Hauptnavigation' => 'Main navigation',
            'Navigation öffnen' => 'Open navigation',
            'Netmaster (Schweiz) AG' => 'Netmaster (Switzerland) Ltd.'
        ]);
    }

    if ($currentRoute === '/en/login') {
        $translations = array_merge($translations, [
            'Login — Netmaster' => 'Login — Netmaster',
            'Netmaster Kundenportal' => 'Netmaster client portal',
            'Willkommen' => 'Welcome',
            'zurück.' => 'back.',
            'Melden Sie sich an, um Ihre Projekte, Dokumente und die Zusammenarbeit mit unserem Team zentral zu verwalten.' => 'Sign in to manage your projects, documents and collaboration with our team in one central place.',
            'Sicher' => 'Secure',
            'Geschützter Zugang' => 'Protected access',
            'Direkt' => 'Direct',
            'Alles an einem Ort' => 'Everything in one place',
            'Persönlich' => 'Personal',
            'Ihr Netmaster Team' => 'Your Netmaster team',
            'Bei Netmaster anmelden' => 'Sign in to Netmaster',
            'Geben Sie Ihre Zugangsdaten ein.' => 'Enter your login details.',
            'Die Eingaben sind gültig. Für den echten Login muss noch das Benutzer-Backend verbunden werden.' => 'Your details are valid. The user authentication backend still needs to be connected for live sign-in.',
            'E-Mail-Adresse' => 'Email address',
            'Passwort' => 'Password',
            'Angemeldet bleiben' => 'Keep me signed in',
            'Passwort vergessen?' => 'Forgot your password?',
            'Anmelden' => 'Sign in',
            'Noch kein Konto?' => 'No account yet?',
            'Jetzt registrieren' => 'Register now',
            'Bitte geben Sie eine gültige E-Mail-Adresse ein.' => 'Please enter a valid email address.',
            'Bitte geben Sie Ihr Passwort ein.' => 'Please enter your password.',
            'Netmaster (Schweiz) AG' => 'Netmaster (Switzerland) Ltd.'
        ]);
    }

    if ($currentRoute === '/en/register') {
        $translations = array_merge($translations, [
            'Registrieren — Netmaster' => 'Register — Netmaster',
            'Netmaster Kundenportal' => 'Netmaster client portal',
            'Gemeinsam mehr.' => 'Achieve more.',
            'Gemeinsam weiter.' => 'Move forward together.',
            'Erstellen Sie Ihr persönliches Konto und starten Sie die direkte, strukturierte Zusammenarbeit mit Netmaster.' => 'Create your personal account and begin a direct, structured collaboration with Netmaster.',
            'Projekte' => 'Projects',
            'Transparent verwalten' => 'Manage transparently',
            'Dokumente' => 'Documents',
            'Sicher austauschen' => 'Share securely',
            'Support' => 'Support',
            'Direkt kommunizieren' => 'Communicate directly',
            'Registrierung' => 'Registration',
            'Konto erstellen' => 'Create account',
            'In wenigen Schritten zu Ihrem Zugang.' => 'Get access in just a few steps.',
            'Ihre Angaben sind vollständig. Für die Kontoerstellung muss noch die Benutzerdatenbank verbunden werden.' => 'Your information is complete. The user database still needs to be connected to create live accounts.',
            'Vorname' => 'First name',
            'Nachname' => 'Last name',
            'Unternehmen' => 'Company',
            'E-Mail-Adresse' => 'Email address',
            'Passwort' => 'Password',
            'Passwort bestätigen' => 'Confirm password',
            'Ich akzeptiere die' => 'I accept the',
            'Datenschutzbestimmungen' => 'privacy policy',
            'Bereits registriert?' => 'Already registered?',
            'Jetzt anmelden' => 'Sign in now',
            'Bitte geben Sie Ihren Vor- und Nachnamen ein.' => 'Please enter your first and last name.',
            'Bitte geben Sie eine gültige E-Mail-Adresse ein.' => 'Please enter a valid email address.',
            'Das Passwort muss mindestens 8 Zeichen lang sein.' => 'The password must contain at least 8 characters.',
            'Die Passwörter stimmen nicht überein.' => 'The passwords do not match.',
            'Bitte akzeptieren Sie die Datenschutzbestimmungen.' => 'Please accept the privacy policy.',
            'Netmaster (Schweiz) AG' => 'Netmaster (Switzerland) Ltd.'
        ]);
    }

    if ($currentRoute === '/en/careers') {
        $translations = array_merge($translations, [
            'Jobs — Netmaster' => 'Careers — Netmaster',
            'Wir verbinden Menschen, Ideen und unternehmerische Möglichkeiten. Entdecken Sie Ihre Perspektive bei Netmaster.' => 'We connect people, ideas and business opportunities. Discover your future at Netmaster.',
            'Offene Stellen ansehen ↓' => 'View open positions ↓',
            'Ihre nächste berufliche Herausforderung.' => 'Your next professional challenge.',
            'Vielen Dank für Ihr Interesse an Netmaster. Sobald neue Stellenangebote verfügbar sind, werden sie auf dieser Seite veröffentlicht.' => 'Thank you for your interest in Netmaster. New opportunities will be published on this page as soon as they become available.',
            'Sie möchten Teil von Netmaster werden, auch wenn aktuell keine passende Stelle ausgeschrieben ist? Senden Sie uns Ihre Spontanbewerbung. Wir freuen uns darauf, Sie kennenzulernen.' => 'Would you like to join Netmaster even though no suitable position is currently advertised? Send us a general application. We look forward to getting to know you.',
            'Vertraulich behandelt' => 'Handled confidentially',
            'Ihre Angaben und Unterlagen werden ausschliesslich für Ihre Bewerbung verwendet.' => 'Your information and documents will be used exclusively for your application.',
            'Ihre Spontanbewerbung wurde erfolgreich validiert. Für den Live-Betrieb muss noch der E-Mail-Versand angeschlossen werden.' => 'Your general application has been validated successfully. Email delivery still needs to be connected for production use.',
            'Gewünschter Bereich' => 'Preferred business area',
            'Immobilien' => 'Real estate',
            'Andere' => 'Other',
            'Ihre Nachricht *' => 'Your message *',
            'Beim Absenden akzeptiere ich die' => 'By submitting, I accept the',
            'Spontanbewerbung senden →' => 'Send general application →',
            'Der Lebenslauf konnte nicht hochgeladen werden.' => 'The CV could not be uploaded.',
            'Bitte laden Sie den Lebenslauf als PDF, DOC oder DOCX hoch.' => 'Please upload your CV as a PDF, DOC or DOCX file.',
            'Der Lebenslauf darf maximal 5 MB gross sein.' => 'The CV must not exceed 5 MB.',
            'Bitte geben Sie Ihren Vornamen ein.' => 'Please enter your first name.',
            'Bitte geben Sie Ihren Nachnamen ein.' => 'Please enter your last name.',
            'Bitte geben Sie eine gültige E-Mail-Adresse ein.' => 'Please enter a valid email address.',
            'Bitte schreiben Sie uns eine kurze Nachricht.' => 'Please write us a short message.',
            'Bitte akzeptieren Sie die Datenschutzvereinbarung.' => 'Please accept the privacy policy.'
        ]);
    }

    $html = strtr($html, $translations);
    $routeMap = [
        'href="/ueber-uns"' => 'href="/en/about-us"',
        'href="/franchising"' => 'href="/en/franchising"',
        'href="/dienstleistungen"' => 'href="/en/services"',
        'href="/kontakt"' => 'href="/en/contact"',
        'href="/stellenangebote"' => 'href="/en/careers"',
        'href="/login"' => 'href="/en/login"',
        'href="/register"' => 'href="/en/register"',
        'href="/marketingmaster.php"' => 'href="/en/marketingmaster"',
        'href="/salesmaster.php"' => 'href="/en/salesmaster"',
        'href="/callmaster"' => 'href="/en/callmaster"',
        'href="/propertymaster.php"' => 'href="/en/propertymaster"',
        'href="/jobsmaster.php"' => 'href="/en/jobsmaster"'
    ];
    $html = strtr($html, $routeMap);
    $germanRoutes = [
        '/en' => '/', '/en/about-us' => '/ueber-uns', '/en/franchising' => '/franchising',
        '/en/services' => '/dienstleistungen', '/en/contact' => '/kontakt', '/en/careers' => '/stellenangebote',
        '/en/login' => '/login', '/en/register' => '/register', '/en/marketingmaster' => '/marketingmaster.php',
        '/en/salesmaster' => '/salesmaster.php', '/en/callmaster' => '/callmaster',
        '/en/propertymaster' => '/propertymaster.php', '/en/jobsmaster' => '/jobsmaster.php'
    ];
    $germanRoute = $germanRoutes[$currentRoute] ?? '/';
    $html = preg_replace('~<a class="dropdown-item active" href="[^"]*">German</a>~', '<a class="dropdown-item" href="' . $germanRoute . '">German</a>', $html);
    $html = preg_replace('~<a class="dropdown-item" href="/en">English</a>~', '<a class="dropdown-item active" href="' . htmlspecialchars($currentRoute) . '">English</a>', $html);
    $html = preg_replace('~(<a class="nav-link dropdown-toggle"[^>]*>)De(</a>)~', '$1En$2', $html);
    echo $html;
}
