<?php
$submitted = $_SERVER['REQUEST_METHOD'] === 'POST';
$fields = [
    'vorname' => trim($_POST['vorname'] ?? ''),
    'nachname' => trim($_POST['nachname'] ?? ''),
    'email' => trim($_POST['email'] ?? ''),
    'telefon' => trim($_POST['telefon'] ?? ''),
    'bereich' => trim($_POST['bereich'] ?? ''),
    'nachricht' => trim($_POST['nachricht'] ?? '')
];
$errors = [];
if ($submitted) {
    if ($fields['vorname'] === '') $errors[] = 'Bitte geben Sie Ihren Vornamen ein.';
    if ($fields['nachname'] === '') $errors[] = 'Bitte geben Sie Ihren Nachnamen ein.';
    if (!filter_var($fields['email'], FILTER_VALIDATE_EMAIL)) $errors[] = 'Bitte geben Sie eine gültige E-Mail-Adresse ein.';
    if ($fields['nachricht'] === '') $errors[] = 'Bitte schreiben Sie uns eine kurze Nachricht.';
    if (!isset($_POST['privacy'])) $errors[] = 'Bitte akzeptieren Sie die Datenschutzvereinbarung.';
    if (isset($_FILES['lebenslauf']) && $_FILES['lebenslauf']['error'] !== UPLOAD_ERR_NO_FILE) {
        if ($_FILES['lebenslauf']['error'] !== UPLOAD_ERR_OK) $errors[] = 'Der Lebenslauf konnte nicht hochgeladen werden.';
        $allowed = ['pdf', 'doc', 'docx'];
        $extension = strtolower(pathinfo($_FILES['lebenslauf']['name'], PATHINFO_EXTENSION));
        if (!in_array($extension, $allowed, true)) $errors[] = 'Bitte laden Sie den Lebenslauf als PDF, DOC oder DOCX hoch.';
        if ($_FILES['lebenslauf']['size'] > 5 * 1024 * 1024) $errors[] = 'Der Lebenslauf darf maximal 5 MB gross sein.';
    }
}
$success = $submitted && !$errors;
?>
<!doctype html>
<html lang="de"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="Aktuelle Stellenangebote bei Netmaster."><title>Jobs — Netmaster</title>
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Manrope:wght@500;600;700;800&display=swap" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="/assets/styles.css" rel="stylesheet"><link href="/assets/logo.css" rel="stylesheet"><link href="/assets/header.css" rel="stylesheet"><link href="/assets/contact-page.css" rel="stylesheet"><link href="/assets/jobs-page.css" rel="stylesheet">
</head><body class="jobs-listing-page">
<header class="site-header"><div class="header-topbar"><div class="container-xl d-flex justify-content-end align-items-center gap-4"><a href="mailto:info@netmaster.ch">✉ info@netmaster.ch</a><a href="tel:+41445424747">☎ +41 44 542 47 47</a></div></div><nav class="navbar navbar-expand-lg" aria-label="Hauptnavigation"><div class="container-xl"><a class="brand" href="/"><img src="/assets/images/logo.png" alt="Netmaster"></a><button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mainNav" aria-label="Navigation öffnen"><span class="navbar-toggler-icon"></span></button><div class="collapse navbar-collapse" id="mainNav"><ul class="navbar-nav ms-auto align-items-lg-center gap-lg-1"><li class="nav-item"><a class="nav-link" href="/ueber-uns">Über uns</a></li><li class="nav-item"><a class="nav-link" href="/franchising">Franchising</a></li><li class="nav-item dropdown"><a class="nav-link dropdown-toggle" href="/dienstleistungen" data-bs-toggle="dropdown">Dienstleistungen</a><ul class="dropdown-menu"><li><a class="dropdown-item" href="/marketingmaster.php">Marketingmaster</a></li><li><a class="dropdown-item" href="/salesmaster.php">Salesmaster</a></li><li><a class="dropdown-item" href="/callmaster">Callmaster</a></li><li><a class="dropdown-item" href="/propertymaster.php">Propertymaster</a></li><li><a class="dropdown-item" href="/jobsmaster.php">Jobsmaster</a></li></ul></li><li class="nav-item"><a class="nav-link active" href="/stellenangebote">Jobs</a></li><li class="nav-item"><a class="nav-link" href="/kontakt">Kontakt</a></li><li class="nav-item dropdown"><a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown">De</a><ul class="dropdown-menu dropdown-menu-end"><li><a class="dropdown-item active" href="/stellenangebote">Deutsch</a></li><li><a class="dropdown-item" href="/it">Italiano</a></li><li><a class="dropdown-item" href="/en">English</a></li></ul></li><li class="nav-item ms-lg-2"><a class="btn btn-cyan login-button" href="/login">Login</a></li></ul></div></div></nav></header>
<main>
<section class="jobs-hero"><div class="jobs-empty-grid" aria-hidden="true"></div><div class="container-xl jobs-hero-inner"><div class="eyebrow fade-up">Karriere bei Netmaster</div><h1 class="fade-up delay-1">Gemeinsam Zukunft<br><span>gestalten.</span></h1><p class="fade-up delay-2">Wir verbinden Menschen, Ideen und unternehmerische Möglichkeiten. Entdecken Sie Ihre Perspektive bei Netmaster.</p><a class="jobs-scroll fade-up delay-3" href="#offene-stellen">Offene Stellen ansehen ↓</a></div></section>

<section id="offene-stellen" class="vacancies-section"><div class="container-xl"><div class="vacancies-heading reveal"><div class="eyebrow dark">Offene Stellen</div><h2>Ihre nächste berufliche Herausforderung.</h2></div><div class="vacancy-empty reveal"><span class="status-dot"></span><div><small>Aktueller Status</small><h3>Momentan sind keine offenen Stellen verfügbar.</h3><p>Vielen Dank für Ihr Interesse an Netmaster. Sobald neue Stellenangebote verfügbar sind, werden sie auf dieser Seite veröffentlicht.</p></div><b>00</b></div></div></section>

<section id="spontanbewerbung" class="application-section"><div class="container-xl"><div class="application-layout"><div class="application-intro reveal"><div class="eyebrow">Spontanbewerbung</div><h2>Vielleicht passen wir trotzdem zusammen.</h2><p>Sie möchten Teil von Netmaster werden, auch wenn aktuell keine passende Stelle ausgeschrieben ist? Senden Sie uns Ihre Spontanbewerbung. Wir freuen uns darauf, Sie kennenzulernen.</p><div class="application-note"><span></span><p><strong>Vertraulich behandelt</strong>Ihre Angaben und Unterlagen werden ausschliesslich für Ihre Bewerbung verwendet.</p></div></div><div class="modern-form-wrap reveal"><?php if ($success): ?><div class="contact-success" role="status"><span>✓</span><h3>Vielen Dank, <?= htmlspecialchars($fields['vorname']) ?>.</h3><p>Ihre Spontanbewerbung wurde erfolgreich validiert. Für den Live-Betrieb muss noch der E-Mail-Versand angeschlossen werden.</p></div>
<?php else: ?>
<?php if ($errors): ?><div class="contact-errors" role="alert"><?= implode('<br>', array_map('htmlspecialchars', $errors)) ?></div><?php endif; ?>
<form method="post" enctype="multipart/form-data" class="modern-contact-form"><div class="form-grid"><label><span>Vorname *</span><input name="vorname" value="<?= htmlspecialchars($fields['vorname']) ?>" required></label><label><span>Nachname *</span><input name="nachname" value="<?= htmlspecialchars($fields['nachname']) ?>" required></label><label><span>E-Mail *</span><input name="email" type="email" value="<?= htmlspecialchars($fields['email']) ?>" required></label><label><span>Telefonnummer</span><input name="telefon" type="tel" value="<?= htmlspecialchars($fields['telefon']) ?>"></label><label class="form-wide"><span>Gewünschter Bereich</span><select name="bereich"><option value="">Bitte auswählen</option><option <?= $fields['bereich'] === 'Marketing' ? 'selected' : '' ?>>Marketing</option><option <?= $fields['bereich'] === 'Sales' ? 'selected' : '' ?>>Sales</option><option <?= $fields['bereich'] === 'Call Center' ? 'selected' : '' ?>>Call Center</option><option <?= $fields['bereich'] === 'Immobilien' ? 'selected' : '' ?>>Immobilien</option><option <?= $fields['bereich'] === 'Human Resources' ? 'selected' : '' ?>>Human Resources</option><option <?= $fields['bereich'] === 'Andere' ? 'selected' : '' ?>>Andere</option></select></label><label class="form-wide"><span>Ihre Nachricht *</span><textarea name="nachricht" rows="5" required><?= htmlspecialchars($fields['nachricht']) ?></textarea></label><label class="form-wide file-field"><span>Lebenslauf</span><input name="lebenslauf" type="file" accept=".pdf,.doc,.docx"><small>PDF, DOC oder DOCX · maximal 5 MB</small></label><label class="privacy-check form-wide"><input type="checkbox" name="privacy" value="1" <?= isset($_POST['privacy']) ? 'checked' : '' ?> required><span>Beim Absenden akzeptiere ich die <a href="/datenschutz">Datenschutzvereinbarung</a>.</span></label><div class="form-wide"><button class="btn btn-cyan rounded-pill" type="submit">Spontanbewerbung senden →</button></div></div></form><?php endif; ?>
</div></div></div></section>
</main>
<footer><div class="container-xl"><div class="footer-main"><a class="brand brand-light" href="/"><img src="/assets/images/logo.png" alt="Netmaster"></a><p>Netmaster (Schweiz) AG<br>Zugerstrasse 162 · CH–8820 Wädenswil</p><div class="footer-links"><a href="/ueber-uns">Über uns</a><a href="/franchising">Franchising</a><a href="/kontakt">Kontakt</a></div></div><div class="footer-bottom"><span>© <?= date('Y') ?> Netmaster</span><span>Impressum · Datenschutz · AGB</span></div></div></footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script><script src="/assets/app.js"></script></body></html>
