<?php
$submitted = $_SERVER['REQUEST_METHOD'] === 'POST';
$email = trim($_POST['email'] ?? '');
$errors = [];
if ($submitted) {
    if (!filter_var($email, FILTER_VALIDATE_EMAIL)) $errors[] = 'Bitte geben Sie eine gültige E-Mail-Adresse ein.';
    if (($_POST['password'] ?? '') === '') $errors[] = 'Bitte geben Sie Ihr Passwort ein.';
}
$success = $submitted && !$errors;
?>
<!doctype html><html lang="de"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="Melden Sie sich bei Ihrem Netmaster Konto an."><title>Login — Netmaster</title>
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Manrope:wght@500;600;700;800&display=swap" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="/assets/styles.css" rel="stylesheet"><link href="/assets/logo.css" rel="stylesheet"><link href="/assets/header.css" rel="stylesheet"><link href="/assets/auth.css" rel="stylesheet">
</head><body class="auth-page">
<header class="site-header"><div class="header-topbar"><div class="container-xl d-flex justify-content-end align-items-center gap-4"><a href="mailto:info@netmaster.ch">✉ info@netmaster.ch</a><a href="tel:+41445424747">☎ +41 44 542 47 47</a></div></div><nav class="navbar navbar-expand-lg"><div class="container-xl"><a class="brand" href="/"><img src="/assets/images/logo.png" alt="Netmaster"></a><button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mainNav"><span class="navbar-toggler-icon"></span></button><div class="collapse navbar-collapse" id="mainNav"><ul class="navbar-nav ms-auto align-items-lg-center gap-lg-1"><li class="nav-item"><a class="nav-link" href="/ueber-uns">Über uns</a></li><li class="nav-item"><a class="nav-link" href="/franchising">Franchising</a></li><li class="nav-item dropdown"><a class="nav-link dropdown-toggle" href="/dienstleistungen">Dienstleistungen</a><ul class="dropdown-menu"><li><a class="dropdown-item" href="/marketingmaster.php">Marketingmaster</a></li><li><a class="dropdown-item" href="/salesmaster.php">Salesmaster</a></li><li><a class="dropdown-item" href="/callmaster">Callmaster</a></li><li><a class="dropdown-item" href="/propertymaster.php">Propertymaster</a></li><li><a class="dropdown-item" href="/jobsmaster.php">Jobsmaster</a></li></ul></li><li class="nav-item"><a class="nav-link" href="/stellenangebote">Jobs</a></li><li class="nav-item"><a class="nav-link" href="/kontakt">Kontakt</a></li><li class="nav-item dropdown"><a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown">De</a><ul class="dropdown-menu dropdown-menu-end"><li><a class="dropdown-item active" href="/login">Deutsch</a></li><li><a class="dropdown-item" href="/it">Italiano</a></li><li><a class="dropdown-item" href="/en">English</a></li></ul></li><li class="nav-item ms-lg-2"><a class="btn btn-cyan login-button active" href="/login">Login</a></li></ul></div></div></nav></header>
<main class="auth-main"><div class="auth-grid" aria-hidden="true"></div><div class="container-xl"><div class="auth-layout">
<section class="auth-copy"><div class="eyebrow fade-up">Netmaster Kundenportal</div><h1 class="fade-up delay-1">Willkommen<span>zurück.</span></h1><p class="fade-up delay-2">Melden Sie sich an, um Ihre Projekte, Dokumente und die Zusammenarbeit mit unserem Team zentral zu verwalten.</p><div class="auth-points fade-up delay-3"><div><strong>Sicher</strong><span>Geschützter Zugang</span></div><div><strong>Direkt</strong><span>Alles an einem Ort</span></div><div><strong>Persönlich</strong><span>Ihr Netmaster Team</span></div></div></section>
<section class="auth-card fade-up delay-2"><div class="auth-card-head"><small>Login</small><h2>Bei Netmaster anmelden</h2><p>Geben Sie Ihre Zugangsdaten ein.</p></div>
<?php if ($success): ?><div class="auth-message success">Die Eingaben sind gültig. Für den echten Login muss noch das Benutzer-Backend verbunden werden.</div><?php endif; ?>
<?php if ($errors): ?><div class="auth-message error" role="alert"><?= implode('<br>', array_map('htmlspecialchars', $errors)) ?></div><?php endif; ?>
<form method="post"><div class="auth-fields"><label class="auth-field full"><span>E-Mail-Adresse</span><input type="email" name="email" value="<?= htmlspecialchars($email) ?>" autocomplete="email" required></label><label class="auth-field full"><span>Passwort</span><input type="password" name="password" autocomplete="current-password" required></label></div><div class="auth-options"><label class="auth-check"><input type="checkbox" name="remember"><span>Angemeldet bleiben</span></label><a href="mailto:info@netmaster.ch?subject=Passwort%20zurücksetzen">Passwort vergessen?</a></div><button class="btn btn-cyan rounded-pill auth-submit" type="submit">Anmelden <span>→</span></button></form><p class="auth-switch">Noch kein Konto? <a href="/register">Jetzt registrieren</a></p></section>
</div></div></main>
<footer><div class="container-xl"><div class="footer-main"><a class="brand brand-light" href="/"><img src="/assets/images/logo.png" alt="Netmaster"></a><p>Netmaster (Schweiz) AG<br>Zugerstrasse 162 · CH–8820 Wädenswil</p><div class="footer-links"><a href="/ueber-uns">Über uns</a><a href="/franchising">Franchising</a><a href="/kontakt">Kontakt</a></div></div><div class="footer-bottom"><span>© <?= date('Y') ?> Netmaster</span><span>Impressum · Datenschutz · AGB</span></div></div></footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script><script src="/assets/app.js"></script></body></html>
