<!doctype html>
<html lang="de"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="Die Business Units von Netmaster: Marketing, Sales, Call Center, Immobilien und Recruiting."><title>Dienstleistungen — Netmaster</title>
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Manrope:wght@500;600;700;800&display=swap" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="/assets/styles.css" rel="stylesheet"><link href="/assets/logo.css" rel="stylesheet"><link href="/assets/header.css" rel="stylesheet"><link href="/assets/services.css" rel="stylesheet">
</head><body class="services-page">
<header class="site-header"><div class="header-topbar"><div class="container-xl d-flex justify-content-end align-items-center gap-4"><a href="mailto:info@netmaster.ch">✉ info@netmaster.ch</a><a href="tel:+41445424747">☎ +41 44 542 47 47</a></div></div><nav class="navbar navbar-expand-lg" aria-label="Hauptnavigation"><div class="container-xl"><a class="brand" href="/"><img src="/assets/images/logo.png" alt="Netmaster"></a><button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mainNav" aria-label="Navigation öffnen"><span class="navbar-toggler-icon"></span></button><div class="collapse navbar-collapse" id="mainNav"><ul class="navbar-nav ms-auto align-items-lg-center gap-lg-1"><li class="nav-item"><a class="nav-link" href="/ueber-uns">Über uns</a></li><li class="nav-item"><a class="nav-link" href="/franchising">Franchising</a></li><li class="nav-item dropdown"><a class="nav-link dropdown-toggle active" href="/dienstleistungen" data-bs-toggle="dropdown">Dienstleistungen</a><ul class="dropdown-menu"><li><a class="dropdown-item" href="/marketingmaster.php">Marketingmaster</a></li><li><a class="dropdown-item" href="/salesmaster.php">Salesmaster</a></li><li><a class="dropdown-item" href="/callmaster">Callmaster</a></li><li><a class="dropdown-item" href="/propertymaster.php">Propertymaster</a></li><li><a class="dropdown-item" href="/jobsmaster.php">Jobsmaster</a></li></ul></li><li class="nav-item"><a class="nav-link" href="/stellenangebote">Jobs</a></li><li class="nav-item"><a class="nav-link" href="/kontakt">Kontakt</a></li><li class="nav-item dropdown"><a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown">De</a><ul class="dropdown-menu dropdown-menu-end"><li><a class="dropdown-item active" href="/dienstleistungen">Deutsch</a></li><li><a class="dropdown-item" href="/it">Italiano</a></li><li><a class="dropdown-item" href="/en">English</a></li></ul></li><li class="nav-item ms-lg-2"><a class="btn btn-cyan login-button" href="/login">Login</a></li></ul></div></div></nav></header>

<main>
<section class="services-hero"><div class="services-grid" aria-hidden="true"></div><div class="container-xl services-hero-inner"><div class="eyebrow fade-up">Unsere Business Units</div><h1 class="fade-up delay-1">Die richtigen Experten<br><span>für jede Herausforderung.</span></h1><p class="fade-up delay-2">Fünf spezialisierte Business Units. Ein gemeinsames Ziel: Ihr Unternehmen mit fundierter Expertise, starken Teams und messbaren Lösungen voranzubringen.</p><a class="services-scroll fade-up delay-3" href="#business-units">Business Units entdecken ↓</a></div></section>

<section id="business-units" class="business-units"><div class="container-xl"><div class="units-heading reveal"><div class="eyebrow dark">Kompetenz aus einer Hand</div><h2>Wählen Sie den Bereich, der Sie weiterbringt.</h2></div><div class="units-grid">
<a class="unit-card unit-marketing reveal" href="/marketingmaster.php"><figure><img src="/assets/images/marketingmaster/group-diverse-people-having-business-meeting-1024x683.jpg" alt="Marketingmaster"></figure><div class="unit-shade"></div><img class="unit-logo" src="/assets/images/business-units/marketingmaster.png" alt=""><div class="unit-content"><small>Online Marketing Agentur</small><h3>Marketingmaster</h3><p>E-Commerce · Webdesign · SEO<br>Virtual Tour · Social Media</p><b>Marketing entdecken ↗</b></div></a>
<a class="unit-card unit-sales reveal" href="/salesmaster.php"><figure><img src="/assets/images/salesmaster/man-giving-bar-graph-presentation-using-high-technology-digital-pen.jpg" alt="Salesmaster"></figure><div class="unit-shade"></div><img class="unit-logo" src="/assets/images/business-units/salesmaster.jpg" alt=""><div class="unit-content"><small>Headhunting Sales</small><h3>Salesmaster</h3><p>Recruiting · Head of Sales<br>Verkaufsleiter · Key Account</p><b>Sales entdecken ↗</b></div></a>
<a class="unit-card unit-call reveal" href="/callmaster"><figure><img src="/assets/images/callmaster/businesswoman-call-center-office.jpg" alt="Callmaster"></figure><div class="unit-shade"></div><img class="unit-logo" src="/assets/images/business-units/callmaster.png" alt=""><div class="unit-content"><small>Call Center</small><h3>Callmaster</h3><p>Telemarketing<br>Digital Lösungen</p><b>Callmaster entdecken ↗</b></div></a>
<a class="unit-card unit-property reveal" href="/propertymaster.php"><figure><img src="/assets/images/propertymaster/luxury-villa.jpg" alt="Propertymaster"></figure><div class="unit-shade"></div><img class="unit-logo" src="/assets/images/business-units/propertymaster.png" alt=""><div class="unit-content"><small>Property</small><h3>Propertymaster</h3><p>Real Estate</p><b>Immobilien entdecken ↗</b></div></a>
<a class="unit-card unit-jobs reveal" href="/jobsmaster.php"><figure><img src="/assets/images/jobsmaster/five-cheerful-business-people-waiting-room.jpg" alt="Jobsmaster"></figure><div class="unit-shade"></div><img class="unit-logo" src="/assets/images/business-units/jobsmaster.png" alt=""><div class="unit-content"><small>Recruiting</small><h3>Jobsmaster</h3><p>Personalvermittlung<br>Diverse Branchen</p><b>Talente entdecken ↗</b></div></a>
</div></div></section>

<section class="services-cta"><div class="container-xl"><div class="services-cta-inner reveal"><div><div class="eyebrow">Nicht sicher, wo Sie starten?</div><h2>Wir finden gemeinsam die passende Lösung.</h2></div><a class="btn btn-dark rounded-pill" href="/kontakt">Projekt besprechen →</a></div></div></section>
</main>
<footer><div class="container-xl"><div class="footer-main"><a class="brand brand-light" href="/"><img src="/assets/images/logo.png" alt="Netmaster"></a><p>Netmaster (Schweiz) AG<br>Zugerstrasse 162 · CH–8820 Wädenswil</p><div class="footer-links"><a href="/ueber-uns">Über uns</a><a href="/franchising">Franchising</a><a href="/kontakt">Kontakt</a></div></div><div class="footer-bottom"><span>© <?= date('Y') ?> Netmaster</span><span>Impressum · Datenschutz · AGB</span></div></div></footer>
<script src="/assets/app.js"></script><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script></body></html>
